fix(backup): error handling in case of cancellation and always release classes (#8659)
this PR makes sure we release Collections when we are done, no matter if there was an error or not, to resolve the issue we have seen before and this because previously we were releasing in case of cancellation only 

it fixes the issue we have seen multiple times 
```
backup <BACKUP_ID> is not yet released, this means its contents have not yet been fully copied to its destination
```

The backup cancellation test was failing because cancelled backups were returning `FAILED` status instead of the expected `CANCELED` status. This was because of backup compression there was cases where cancellation wasn't handled, after debugging by log the error it was return error like this 

```
backup_journey.go:299: error: write backup header in file ./data: gcsbackup/Tenant2/lsm/objects/segment-1753099884917903496.secondary.0.bloom: io: read/write on closed pipe
```